SELECT * FROM customer limit(10)

--TOTAL REVENUE GENERATED BY MALE AND FEMALE
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender;

--WHICH CUSTOMER USED DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT 
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied='Yes' AND purchase_amount >=(SELECT AVG(purchase_amount) FROM customer);

--TOP 5 PRODUCTS WITH HIGHEST AVERAGE REVIEW RATING 
SELECT item_purchased,
       ROUND(AVG(review_rating)::numeric, 2) AS "Average Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating)
LIMIT 5;

--COMPARE AVERAGE PURCHASED AMOUNT BETWEEN STANDARDS AND EXPRESSS SHIPPING
SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2) 
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

--DO SUBSCRIBE CUSTOMER SPEND MORE? COMPARE AVERAGE SPEND AND TOTAL REVENUE BETWEEN SUBSCRIBERS AND NON SUBSCRIERS
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount)::numeric, 2) AS avg_spend,
    ROUND(SUM(purchase_amount)::numeric, 2) AS total_spend
FROM customer
GROUP BY subscription_status
ORDER BY total_spend DESC, avg_spend DESC;

--WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASE WITH DISCOUNT APPLIED
SELECT 
    item_purchased,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--SEGMENT CUSTOMERS INTO NEW, RETURNING AND LOYAL BASED ON THEIR TOTAL NUMBER OF PREVIOUS PURCHASE AND SHOW THE COUNT OF EACH SEGMENT.
SELECT
    CASE
        WHEN previous_purchases < 5 THEN 'New'
        WHEN previous_purchases BETWEEN 5 AND 20 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment
ORDER BY customer_count DESC;

--THE TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

--ARE CUSTOMERS WHO ARE REPEAT BUYERS (MORE THAN 5 PREVIOUS PURCHASES) ALSO LIKELY TO SUBSCRIBE?
SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--WITH PERCENTAGE 
SELECT
    subscription_status,
    COUNT(*) AS repeat_buyers,
    ROUND(
        COUNT(*) * 100.0 /
        SUM(COUNT(*)) OVER (),
        2
    ) AS percentage
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--WHAT IS THE REVENUE CONTRIBUTION OF EACH AGE GROUP?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;